=== AStatler/JIRA-Spec-Artifacts/schemas/specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="workgroups.xsd"/>
  <xs:element name="specification">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="artifactPageExtension" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="value" type="xs:NMTOKEN" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="artifacts" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required"/>
            <xs:attribute name="name" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[^\s]*([\s]+[^\s]+)*"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional"/>
            <xs:attribute name="deprecated" type="xs:boolean" default="false"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="pages" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="otherPages" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="url" type="xs:NMTOKEN" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required"/>
            <xs:attribute name="name" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[^\s]*([\s]+[^\s]+)*"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional"/>
            <xs:attribute name="deprecated" type="xs:boolean" default="false"/>
            <xs:attribute name="url" type="xs:NMTOKEN" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="url" type="xs:anyURI" use="optional"/>
      <xs:attribute name="ciUrl" type="xs:anyURI" use="optional"/>
      <xs:attribute name="ballotUrl" type="xs:anyURI" use="optional"/>
      <xs:attribute name="defaultWorkgroup" type="WorkGroup" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="website">
    <xs:restriction base="xs:anyURI">
      <xs:pattern value="http(.)+[^\\/^\\s]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== AStatler/JIRA-Spec-Artifacts/FHIR-cqif.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification defaultWorkgroup="cds" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="ActivityDefinition" key="ActivityDefinition" deprecated="true"/>
  <artifacts name="DecisionSupportServiceModule" key="DecisionSupportServiceModule" deprecated="true"/>
  <artifacts name="GuidanceResponse" key="GuidanceResponse" deprecated="true"/>
  <artifacts name="Library" key="Library" deprecated="true"/>
  <artifacts name="Measure" key="Measure" deprecated="true"/>
  <artifacts name="MeasureReport" key="MeasureReport" deprecated="true"/>
  <artifacts name="PlanDefinition" key="PlanDefinition" deprecated="true"/>
  <artifacts name="Questionnaire" key="Questionnaire" deprecated="true"/>
  <artifacts name="QuestionnaireResponse" key="QuestionnaireAnswers" deprecated="true"/>
  <artifacts name="ValueSet" key="ValueSet" deprecated="true"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(profiles)" key="profiles"/>
  <pages name="Clinical Reasoning Module" key="clinicalreasoning-module" url="clinicalreasoning-module" deprecated="true"/>
  <pages name="cqif-cds-on-fhir" key="cqif-cds-on-fhir" url="cqif-cds-on-fhir" deprecated="true"/>
  <pages name="cqif-knowledge-artifact-distribution" key="cqif-knowledge-artifact-distribution" url="cqif-knowledge-artifact-distribution" deprecated="true"/>
  <pages name="cqif-knowledge-artifact-representation" key="cqif-knowledge-artifact-representation" url="cqif-knowledge-artifact-representation" deprecated="true"/>
  <pages name="cqif-quality-reporting" key="cqif-quality-reporting" url="cqif-quality-reporting" deprecated="true"/>
  <pages name="cqif-topics-definitional-resources" key="cqif-topics-definitional-resources" url="cqif-topics-definitional-resources" deprecated="true"/>
  <pages name="cqif-topics-using-expressions" key="cqif-topics-using-expressions" url="cqif-topics-using-expressions" deprecated="true"/>
  <pages name="Home (index)" key="index" url="index"/>
</specification>
