=== AStatler/JIRA-Spec-Artifacts/schemas/specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="workgroups.xsd"/>
  <xs:element name="specification">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="artifactPageExtension" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="value" type="xs:NMTOKEN" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="artifacts" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required"/>
            <xs:attribute name="name" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[^\s]*([\s]+[^\s]+)*"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional"/>
            <xs:attribute name="deprecated" type="xs:boolean" default="false"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="pages" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="otherPages" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="url" type="xs:NMTOKEN" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required"/>
            <xs:attribute name="name" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[^\s]*([\s]+[^\s]+)*"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional"/>
            <xs:attribute name="deprecated" type="xs:boolean" default="false"/>
            <xs:attribute name="url" type="xs:NMTOKEN" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="url" type="xs:anyURI" use="optional"/>
      <xs:attribute name="ciUrl" type="xs:anyURI" use="optional"/>
      <xs:attribute name="ballotUrl" type="xs:anyURI" use="optional"/>
      <xs:attribute name="defaultWorkgroup" type="WorkGroup" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="website">
    <xs:restriction base="xs:anyURI">
      <xs:pattern value="http(.)+[^\\/^\\s]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== AStatler/JIRA-Spec-Artifacts/FHIR-us-daf-research.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/us/daf" ciUrl="https://build.fhir.org/ig/HL7/daf-research" defaultWorkgroup="fhir-i" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="Patient" key="Patient"/>
  <artifacts name="ResearchStudy" key="ResearchStudy"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(profiles)" key="profiles"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/CDA-core.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This data is just for testing purposes and is not complete -->
<specification defaultWorkgroup="sd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifacts name="SomeClass" key="someclass"/>
  <artifacts name="SomeOtherClass" key="someotherclass"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(methodology)" key="methodology"/>
  <pages name="(profiles)" key="profiles"/>
  <pages name="Intro" key="intro"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-ecr.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/uv/ecr" ciUrl="http://build.fhir.org/ig/HL7/case-reporting" defaultWorkgroup="pher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="CodeSystem" key="CodeSystem" deprecated="true"/>
  <artifacts name="Composition" key="Composition" deprecated="true"/>
  <artifacts name="Encounter" key="Encounter" deprecated="true"/>
  <artifacts name="StructureDefinition" key="StructureDefinition" deprecated="true"/>
  <artifacts name="ValueSet" key="ValueSet" deprecated="true"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(profiles)" key="profiles"/>
  <pages name="Ballot Intro" key="ballot-intro" url="ballot-intro" deprecated="true"/>
  <pages name="Element" key="element" url="element" deprecated="true"/>
  <pages name="Home (index)" key="index" url="index"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-immds.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/uv/immds" ciUrl="http://build.fhir.org/ig/HL7/ImmunizationFHIRDS" defaultWorkgroup="pher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="Immunization" key="Immunization" deprecated="true"/>
  <artifacts name="ImmunizationRecommendation" key="ImmunizationRecommendation" deprecated="true"/>
  <artifacts name="Patient" key="Patient" deprecated="true"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(profiles)" key="profiles"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-us-qicore.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/us/qicore" ciUrl="https://build.fhir.org/ig/cqframework/qi-core" defaultWorkgroup="cqi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="AllergyIntolerance" key="AllergyIntolerance"/>
  <artifacts name="Condition" key="Condition"/>
  <artifacts name="Encounter" key="Encounter"/>
  <artifacts name="Goal" key="Goal"/>
  <artifacts name="ImagingStudy" key="ImagingStudy"/>
  <artifacts name="MedicationRequest" key="MedicationPrescription"/>
  <artifacts name="Patient" key="Patient"/>
  <artifacts name="StructureDefinition" key="StructureDefinition"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(profiles)" key="profiles"/>
  <pages name="Home (index)" key="index" url="index"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-us-core.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/us/core" ciUrl="http://build.fhir.org/ig/HL7/US-Core" defaultWorkgroup="us-realm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="AllergyIntolerance" key="AllergyIntolerance" deprecated="true"/>
  <artifacts name="AuditEvent" key="AuditEvent" deprecated="true"/>
  <artifacts name="CarePlan" key="CarePlan" deprecated="true"/>
  <artifacts name="CareTeam" key="CareTeam" deprecated="true"/>
  <artifacts name="Composition" key="Composition" deprecated="true"/>
  <artifacts name="Condition" key="Condition" deprecated="true"/>
  <artifacts name="DiagnosticRequest (see ServiceRequest)" key="DiagnosticRequest" deprecated="true"/>
  <artifacts name="DiagnosticReport" key="DiagnosticReport" deprecated="true"/>
  <artifacts name="DocumentReference" key="DocumentReference" deprecated="true"/>
  <artifacts name="Encounter" key="Encounter" deprecated="true"/>
  <artifacts name="FamilyMemberHistory" key="FamilyHistory" deprecated="true"/>
  <artifacts name="Immunization" key="Immunization" deprecated="true"/>
  <artifacts name="List" key="List" deprecated="true"/>
  <artifacts name="Location" key="Location" deprecated="true"/>
  <artifacts name="Measure" key="Measure" deprecated="true"/>
  <artifacts name="MedicationAdministration" key="MedicationAdministration" deprecated="true"/>
  <artifacts name="MedicationRequest" key="MedicationPrescription" deprecated="true"/>
  <artifacts name="Observation" key="Observation" deprecated="true"/>
  <artifacts name="Organization" key="Organization" deprecated="true"/>
  <artifacts name="Patient" key="Patient" deprecated="true"/>
  <artifacts name="Practitioner" key="Practitioner" deprecated="true"/>
  <artifacts name="PractitionerRole" key="PractitionerRole" deprecated="true"/>
  <artifacts name="Procedure" key="Procedure" deprecated="true"/>
  <artifacts name="Provenance" key="Provenance" deprecated="true"/>
  <artifacts name="Specimen" key="Specimen" deprecated="true"/>
  <artifacts name="StructureDefinition" key="StructureDefinition" deprecated="true"/>
  <artifacts name="ValueSet" key="ValueSet" deprecated="true"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(methodology)" key="methodology"/>
  <pages name="(profiles)" key="profiles"/>
  <pages name="Schemas &amp; Schematrons" key="schemas-schematrons" deprecated="true"/>
  <pages name="Argnonauts" key="argonauts" url="argnonauts" deprecated="true"/>
  <pages name="Home (index)" key="index" url="index" deprecated="true"/>
  <pages name="Implementation Registry (registry/iglist)" key="iglist" url="registry" deprecated="true"/>
  <pages name="Terminologies - Systems" key="terminologies-systems" url="terminologies-systems" deprecated="true"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-us-ccda.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/us/ccda" ciUrl="https://build.fhir.org/ig/HL7/ccda-on-fhir" defaultWorkgroup="sd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="AuditEvent" key="AuditEvent" deprecated="true"/>
  <artifacts name="Composition" key="Composition" deprecated="true"/>
  <artifacts name="Provenance" key="Provenance" deprecated="true"/>
  <artifacts name="StructureDefinition" key="StructureDefinition" deprecated="true"/>
  <artifacts name="ValueSet" key="ValueSet" deprecated="true"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(methodology)" key="methodology"/>
  <pages name="(profiles)" key="profiles"/>
  <pages name="Implementation (see Documentation)" key="implementation" url="implementation" deprecated="true"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-us-breastcancer.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/us/breastcancer" ciUrl="https://build.fhir.org/ig/HL7/us-breastcancer" defaultWorkgroup="cic" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="Observation" key="Observation" deprecated="true"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(profiles)" key="profiles"/>
</specification>
