=== AStatler/JIRA-Spec-Artifacts/schemas/specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="workgroups.xsd"/>
  <xs:element name="specification">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="artifactPageExtension" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="value" type="xs:NMTOKEN" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="artifacts" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required"/>
            <xs:attribute name="name" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[^\s]*([\s]+[^\s]+)*"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional"/>
            <xs:attribute name="deprecated" type="xs:boolean" default="false"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="pages" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="otherPages" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="url" type="xs:NMTOKEN" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="key" type="xs:NMTOKEN" use="required"/>
            <xs:attribute name="name" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[^\s]*([\s]+[^\s]+)*"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="workgroup" type="WorkGroup" use="optional"/>
            <xs:attribute name="deprecated" type="xs:boolean" default="false"/>
            <xs:attribute name="url" type="xs:NMTOKEN" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="url" type="xs:anyURI" use="optional"/>
      <xs:attribute name="ciUrl" type="xs:anyURI" use="optional"/>
      <xs:attribute name="ballotUrl" type="xs:anyURI" use="optional"/>
      <xs:attribute name="defaultWorkgroup" type="WorkGroup" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="website">
    <xs:restriction base="xs:anyURI">
      <xs:pattern value="http(.)+[^\\/^\\s]"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== AStatler/JIRA-Spec-Artifacts/FHIR-phd.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/uv/phd" defaultWorkgroup="dev" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="Device" key="Device" deprecated="true"/>
  <artifacts name="Observation" key="Observation" deprecated="true"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(profiles)" key="profiles"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-genomics-reporting.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/uv/genomics-reporting" ciUrl="http://build.fhir.org/ig/HL7/genomics-reporting" defaultWorkgroup="cg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="Observation" key="Observation"/>
  <artifacts name="Sequence" key="Sequence"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(profiles)" key="profiles"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-sdc.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/us/sdc" ciUrl="https://build.fhir.org/ig/HL7/sdc" defaultWorkgroup="fhir-i" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="CapabilityStatement (Conformance)" key="Conformance" deprecated="true"/>
  <artifacts name="DataElement (see StructureDefinition)" key="DataElement" deprecated="true"/>
  <artifacts name="Questionnaire" key="Questionnaire" deprecated="true"/>
  <artifacts name="QuestionnaireResponse" key="QuestionnaireAnswers" deprecated="true"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(methodology)" key="methodology"/>
  <pages name="(profiles)" key="profiles"/>
  <pages name="Home (index)" key="index" url="index"/>
  <pages name="Implementation Registry (registry/iglist)" key="iglist" url="registry" deprecated="true"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-vhdir.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/uv/vhdir" ciUrl="http://build.fhir.org/ig/HL7/VhDir" defaultWorkgroup="pa" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="Organization" key="Organization" deprecated="true"/>
  <artifacts name="OrganizationRole" key="OrganizationRole" deprecated="true"/>
  <artifacts name="Practitioner" key="Practitioner" deprecated="true"/>
  <artifacts name="PractitionerRole" key="PractitionerRole" deprecated="true"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(profiles)" key="profiles"/>
  <pages name="Home (index)" key="index" url="index"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-ips.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/uv/ips" ciUrl="http://build.fhir.org/ig/HL7/fhir-ips" defaultWorkgroup="pa" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="Patient" key="Patient"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(profiles)" key="profiles"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-us-argonaut.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://www.fhir.org/guides/argonaut" ciUrl="https://build.fhir.org/ig/argonautproject/data-query" defaultWorkgroup="us-realm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="AuditEvent" key="AuditEvent"/>
  <artifacts name="Provenance" key="Provenance"/>
  <artifacts name="StructureDefinition" key="StructureDefinition"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(profiles)" key="profiles"/>
  <pages name="Argnonauts" key="argonauts" url="argnonauts" deprecated="true"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-us-lab.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification defaultWorkgroup="oo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="Observation" key="Observation"/>
  <artifacts name="ValueSet" key="ValueSet"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(profiles)" key="profiles"/>
  <pages name="Terminologies - Systems" key="terminologies-systems" url="terminologies-systems"/>
</specification>

=== AStatler/JIRA-Spec-Artifacts/FHIR-sdc-de.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification url="http://hl7.org/fhir/us/sdcde" ciUrl="http://build.fhir.org/ig/HL7/sdc-de" defaultWorkgroup="fhir-i" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specification.xsd">
  <artifactPageExtension value="-definitions"/>
  <artifactPageExtension value="-examples"/>
  <artifactPageExtension value="-mappings"/>
  <artifacts name="DataElement (see StructureDefinition)" key="DataElement" deprecated="true"/>
  <pages name="(NA)" key="NA"/>
  <pages name="(many)" key="many"/>
  <pages name="(profiles)" key="profiles"/>
  <pages name="ElementDefinition" key="elementdefinition" url="elementdefinition" deprecated="true"/>
</specification>
