=== AStatler/JIRA-Spec-Artifacts/schemas/specificationList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="specifications">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="specification" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="key" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:NMTOKEN">
                  <xs:pattern value="[a-z\-]+"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="name" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[A-Z][^\s]*([\s]+[^\s]+)*"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="familyPrefix" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:pattern value="[A-Z]+\-"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AStatler/JIRA-Spec-Artifacts/SPECS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--WARNING: This is a generated file.  It is derived from all other SPEC-* files.  DO NOT EDIT.-->
<specifications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/specificationList.xsd">
<specification key="CDA-core" name="Clinical Document Architecture (CDA) Core"/>
<specification key="CDA-someig" name="Some CDA IG"/>
<specification key="FHIR-core" name="FHIR Core"/>
<specification key="FHIR-fhirpath" name="FHIRPath"/>
<specification key="FHIR-smart" name="SMART on FHIR"/>
<specification key="FHIR-ecr" name="Electronic Case Reporting"/>
<specification key="FHIR-genomics-reporting" name="Genomics Reporting"/>
<specification key="FHIR-immds" name="CDS Immunization Forecast"/>
<specification key="FHIR-ips" name="International Patient Summary"/>
<specification key="FHIR-phd" name="Personal Healthcare Devices"/>
<specification key="FHIR-pocd" name="Point of Care Devices"/>
<specification key="FHIR-sdc" name="Structured Data Capture (SDC)"/>
<specification key="FHIR-sdc-de" name="Structured Data Capture (SDC-DE)"/>
<specification key="FHIR-vhdir" name="Validated Healthcare Directory"/>
<specification key="FHIR-us-core" name="US Core"/>
<specification key="FHIR-us-breastcancer" name="US Breast Cancer"/>
<specification key="FHIR-us-ccda" name="US C-CDA on FHIR"/>
<specification key="FHIR-us-daf-research" name="US DAF Research"/>
<specification key="FHIR-us-hai" name="US Healthcare Associated Infections"/>
<specification key="FHIR-us-pharmacy" name="US Pharmacy"/>
<specification key="FHIR-us-qicore" name="US QI Core"/>
<specification key="FHIR-cqif" name="Clinical Quality Information Framework (CQIF)" deprecated="true"/>
<specification key="FHIR-gao" name="Guideline Appropriate Ordering (GAO)" deprecated="true"/>
<specification key="FHIR-us-argonaut" name="Argonaut (do not use)" deprecated="true"/>
<specification key="FHIR-us-lab" name="US Lab" deprecated="true"/>
</specifications>

=== AStatler/JIRA-Spec-Artifacts/xml/SPECS-FHIR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  - A list of all specifications associated with the FHIR product family (and managed through the FHIR specification tracker)
  - Sort order reflects the order specifications will appear in the drop-down
  - The primary (default) specification should have a key of 'core'
  -
  - WARNING: Don't *ever* change the key as you'll break old tracker specifications.  Leave the key the same and change the name only.
  -->
<specifications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/specificationList.xsd">
	<specification key="core" name="FHIR Core"/>
	<specification key="cds-hooks" name="CDS Hooks"/>
	<specification key="fhirpath" name="FHIRPath"/>
	<specification key="smart" name="SMART on FHIR"/>
	<specification key="ecr" name="Electronic Case Reporting"/>
	<specification key="genomics-reporting" name="Genomics Reporting"/>
	<specification key="immds" name="CDS Immunization Forecast"/>
	<specification key="ips" name="International Patient Summary"/>
	<specification key="phd" name="Personal Healthcare Devices"/>
	<specification key="pocd" name="Point of Care Devices"/>
	<specification key="sdc" name="Structured Data Capture (SDC)"/>
	<specification key="sdc-de" name="Structured Data Capture (SDC-DE)"/>
	<specification key="vhdir" name="Validated Healthcare Directory"/>
	<specification key="us-core" name="US Core"/>
	<specification key="us-breastcancer" name="US Breast Cancer"/>
	<specification key="us-ccda" name="US C-CDA on FHIR"/>
	<specification key="us-daf-research" name="US DAF Research"/>
	<specification key="us-hai" name="US Healthcare Associated Infections"/>
	<specification key="us-pharmacy" name="US Pharmacy"/>
	<specification key="us-qicore" name="US QI Core"/>
	<specification key="cqif" name="Clinical Quality Information Framework (CQIF)" deprecated="true"/>
	<specification key="gao" name="Guideline Appropriate Ordering (GAO)" deprecated="true"/>
	<specification key="us-argonaut" name="Argonaut (do not use)" deprecated="true"/>
	<specification key="us-lab" name="US Lab" deprecated="true"/>
</specifications>
