=== AStatler/JIRA-Spec-Artifacts/schemas/workgroupList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 rel. 2 sp1 (x64) (http://www.altova.com) by Lloyd McKenzie (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="workgroups">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="workgroup" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="key" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:NMTOKEN">
                  <xs:pattern value="[a-z\-]+"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="name" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[A-Z][^\s]*([\s]+[^\s]+)*"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="deprecated" type="xs:boolean" default="false"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AStatler/JIRA-Spec-Artifacts/workgroups.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  - A list of all work groups (and other HL7 groups/individuals) that can have responsibility for change requests
  -
  - WARNING: Don't *ever* change the key as you'll break old tracker workgroups.  Leave the key the same and change the name only.  
  -          No one sees the key except when maintaining these files or working with exports
  -->
<workgroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schemas/workgroupList.xsd">
	<workgroup key="brr" name="Biomedical Research &amp;amp; Regulation"/>
	<workgroup key="cbcc" name="Community-Based Care and Privacy"/>
	<workgroup key="cgit" name="Conformance"/>
	<workgroup key="cds" name="Clinical Decision Support"/>
	<workgroup key="cic" name="Clinical Interoperability Council"/>
	<workgroup key="cg" name="Clinical Genomics"/>
	<workgroup key="cqi" name="Clinical Quality Information"/>
	<workgroup key="dev" name="Devices"/>
	<workgroup key="ehr" name="Electronic Health Record"/>
	<workgroup key="fhir-tools-core" name="FHIR Core Tooling/Pubs"/>
	<workgroup key="director" name="FHIR Director"/>
	<workgroup key="fgb" name="FHIR Governance Board"/>
	<workgroup key="fhir-tools-ig" name="FHIR IG Tooling/Pubs"/>
	<workgroup key="fhir-i" name="FHIR Infrastructure"/>
	<workgroup key="fmg" name="FHIR Mgmt Group" deprecated="true"/>
	<workgroup key="fm" name="Financial Mgmt"/>
	<workgroup key="hsi" name="Health Standards Integration"/>
	<workgroup key="project" name="IG Project"/>
	<workgroup key="its" name="Implementable Technology Specifications"/>
	<workgroup key="ii" name="Imaging Integration"/>
	<workgroup key="inm" name="Infrastructure &amp;amp; Messaging"/>
	<workgroup key="mnm" name="Modeling &amp;amp; Methodology"/>
	<workgroup key="oo" name="Orders &amp;amp; Observations"/>
	<workgroup key="pa" name="Patient Administration"/>
	<workgroup key="pc" name="Patient Care"/>
	<workgroup key="pharm" name="Pharmacy"/>
	<workgroup key="pher" name="Public Health"/>
	<workgroup key="pubs" name="Publishing"/>
	<workgroup key="security" name="Security"/>
	<workgroup key="soa" name="Service Oriented Architecture"/>
	<workgroup key="sd" name="Structured Documents"/>
	<workgroup key="templates" name="Templates"/>
	<workgroup key="us-realm" name="US Realm Task Force"/>
	<workgroup key="vocab" name="Vocabulary"/>
</workgroups>
